apiVersion: apps/v1
kind: Deployment
metadata:
  name: squad4-meme-generator-backend
spec:
  replicas: 1
  selector:
    matchLabels: 
      app.kubernetes.io/instance: squad4-meme-generator-backend
      app.kubernetes.io/name: squad4-meme-generator-backend
  template: 
    metadata:
      labels:
        app.kubernetes.io/instance: squad4-meme-generator-backend
        app.kubernetes.io/name: squad4-meme-generator-backend
    spec:
      containers:
      - name: squad4-meme-generator-backend
        image: quay.io/levandrejev/squad4-meme-generator-backend:446ee3d77fd2552dbcc37351fe4eaa4fb6c3ef81
        